### ISSUE TITLE
callback not called when using template url

### ISSUE THREAD

**Issue by ydaniels** [derlin/semantic-modals#2] opened 2017-03-15 13:18 UTC
Callback is not fired when using templateUrl for modal whether you approve or you deny

**Comment by derlin** [comment] 2017-03-15 14:08
Can you give me more info ? I couldn't reproduce it (I use it for example in the gh-pages branch without any troubles).

**Comment by ydaniels** [comment] 2017-03-15 18:07
a situation where you have in html : 

`<button ng-click=showModal()>Show</button>`

in your controller:

```
$scope.showModal = function(){
ModalService.showModal( {
      templateUrl: "semanticModal.html",
     

  } ).then( function( result ){
      console.log( result );
      //this doesnt work
  }, function(){
      console.log( "error" );
 //this doesnt work too 
      
  } );
```
}

**Comment by derlin** [comment] 2017-03-16 10:37
If you use a template, it is your responsibility to call the `close` method available in the modal scope. It means that in your template's buttons, you need to have an attribute like `ng-click="close(true)"`. Without a call to `close`, the _success callback_ will indeed never be called.

Here is an example of buttons:

    <div class="ui black deny button" ng-click="close(false)">Cancel</div>
    <div class="ui positive right button" ng-click="close(true)">Save</div>

The boolean parameter of the `close` function will then be available in the `result.status` field in the callback. 

Let me know if this still does not work.

---------------------

_Side note_: a new version of the project, (DerlinModals)[https://github.com/derlin/DerlinModals] is more thoroughly documented.

**Comment by derlin** [comment] 2017-09-05 11:54
closing the issue.

**Closed as completed by derlin** 2017-09-05 11:54 UTC
